### ISSUE TITLE
Differing versions for 32bit 64bit

### ISSUE THREAD

**Issue by shaggytwodope** [linuxlite/litesoftware#2]
Looking at http://repo.linuxliteos.com/linuxlite/pool/main/l/lite-software/

I see different versions, I'd like to know why. So I can add a changelog and we can tag accordingly.
This would make the versioning and releases simpler if the versions match, even when no major changes are made to the other arch. More importantly, if we can list the 64bit/32bit specific issues maybe we can add a check for them and simplifiy the repo?

**Comment by linuxlite** [comment]
One has Steam in the list (64bit) the 32bit does not since it is already installed in LL 32bit.

**Comment by shaggytwodope** [comment]
This is addressed in #3, I'll add changelog and such after this is tested.
