### ISSUE TITLE
Remove Software - if there is nothing to remove

### ISSUE THREAD

**Issue by linuxlite** [linuxlite/litesoftware#24]
Remove Software - if there is nothing to remove, suggest a pop up dialogue that informs the user of this, then when user clicks 'OK' it takes them back to the task selector.

**Comment by niyasc** [comment]
Instead of that, why not check for installation status and
- Remove/Disable install button if software is already installed
- Remove/Disable remove button if software is not installed?

**Comment by ralphys** [comment]
@niyasc 
Unfortunately that's not possible. lite-software is zenity + bash scripts.

**Comment by niyasc** [comment]
`dpkg-query -s` or `dpkg-query --status` can be used to check installation status of packages, if possible.


>        -s, --status package-name...
>               Report status of specified package. This just displays the
>               entry in the installed package status database. When multiple
>               package-name are listed, the requested status entries are
>               separated by an empty line, with the same order as specified
>               on the argument list.
