### ISSUE TITLE
Remove status category, and have applications show up based on context

### ISSUE THREAD

**Issue by AdrianKoshka** [linuxlite/litesoftware#4]
The basic idea is to improve readability, this idea was thought up by @shaggytwodope.

- Only show items to be installed on an "install" prompt
- Only show items to be removed on a "remove" prompt
  - This renders the status category useless.
    - Improving readability
    - Improving simplicity

CC @Misko-2083 @linuxlite

**Comment by Misko-2083** [comment]
@AdrianKoshka I think it is very handy to list both, installed and not installed, in one place. Otherwise users would have to open the remove dialog to see what packages are installed.

**Comment by shaggytwodope** [comment]
@Misko-2083 That is a fair point. I think I'd like to refine the idea a bit more then. Could we trim down the amount of text in the Description?

Example:

Watch Apple trailers in your web browser = Perfectly fine.

This will install Pidgin... etc = Well it's an installer so the "This will install" part is not needed.

Summary of the idea is to show as little text as possible but get the point across well. Some people with reading disablities have a hard time dealing with large amounts of text. (I dont intend to break functionality just word things a bit better)

Is anyone against this idea of trimming text a bit, I'll open PR later if everyone is cool with that.

**Comment by Misko-2083** [comment]
@shaggytwodope That is a very good idea. :+1:

**Comment by AdrianKoshka** [comment]
@shaggytwodope sounds good to me.

**Comment by shaggytwodope** [comment]
Going to keep this open as a todo list of sorts, helps me track stuff to do.

**Comment by AdrianKoshka** [comment]
Okay, fair enough.
