### ISSUE TITLE
32bit & 64bit Lite Software - Install/Remove Software shows ALL software installed

### ISSUE THREAD

**Issue by linuxlite** [linuxlite/litesoftware#8]
@gerito1 on a fresh install of Linux Lite 2.2 64bit, I run Lite Software and after running 'Updating Sources', I click on 'Install Software' on the first window:

![](http://i.imgur.com/sWrOd18.png)

The list displays correctly:

![](http://i.imgur.com/VvfYHNv.png)

I then click on 'Cancel' on that window, then select 'Remove Software' from Lite Software, and it shows everything is installed on the 'Remove Additional Software' window when I have installed nothing:

![](http://i.imgur.com/3oFPlPv.png)

I then cancel that window and go back to the Lite Software selector, and now the 'Install Additional Software' window shows everything installed:

![](http://i.imgur.com/NncWkN4.png)

Something very strange happening here, can you please look into this? Thank you.

**Comment by linuxlite** [comment]
@gerito1 I've just noticed the last commit you offered works fine. Looks like something went bad after I had made some cosmetic changes, so your old code is good, can you please take a look at the new commit and see why it is doing this. Sorry for the inconvenience.

**Comment by linuxlite** [comment]
@gerito1 Don't check this just yet, I'll post an updated message and code soon, I think I've found the issue.

**Comment by linuxlite** [comment]
All fixed :smiley:

**Comment by gerito1** [comment]
@linuxlite Oh shit, I didn't know how to hold my butt there XD.
Ok, then all good. I'm checking the changes, but I'm busy now.
I will tell you If I found something.
