### ISSUE TITLE
Modify script to show percentage progress where possible [$20]

### ISSUE THREAD

**Issue by linuxlite** [linuxlite/litesoftware#9]
@gerito1 If I created a $20 Bounty for this, would you be interested in modifying the updates-gui script to show percentage progress instead of pulsate on the zenity dialogues wherever possible?

**Comment by gerito1** [comment]
@linuxlite 
I could give a look. But at this moment I'm a little busy.
I cannot promise anything right now, maybe tomorrow, the Friday, but more likely this weekend.
Feel free to do as you think is convenient, but I don't necessarily will claim a bounty this time.

**Comment by linuxlite** [comment]
@gerito1 Thank you, we're releasing this on the 1st April, so I am hoping to have this tweaked and tested a week before, that gives us until just after the weekend to be safe. Would appreciate any assistance here and more than happy to give you something for it.

**Comment by linuxlite** [comment]
Issue resolved by original developer.
